### ISSUE TITLE
meld3 1.0.2 is breaking supervisor

### ISSUE THREAD

**Issue by rtsai123** [Supervisor/meld3#22]
Hi the latest meld3 is breaking supervisor.  If we downgrade meld3 to 1.0.1 supervisor works.

:~#  /etc/init.d/supervisor start
Starting supervisor: /usr/bin/dirname: extra operand `.pid'
Try `/usr/bin/dirname --help' for more information.
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5
                                                           [FAILED]
:~# pip list | grep meld3
meld3 (1.0.2)

#
supervisor (3.1.3)

**Comment by rtsai123** [comment]
:~# pip install meld3==1.0.1
Collecting meld3==1.0.1
  Downloading meld3-1.0.1.tar.gz
Installing collected packages: meld3
  Found existing installation: meld3 1.0.2
    Uninstalling meld3-1.0.2:
      Successfully uninstalled meld3-1.0.2
  Running setup.py install for meld3
Successfully installed meld3-1.0.1
:~# /etc/init.d/supervisor start
Starting supervisor: /usr/bin/dirname: extra operand `.pid'
Try `/usr/bin/dirname --help' for more information.

**Comment by mnaberez** [comment]
I am not able to duplicate this.  Supervisor 3.1.3 installs and runs fine for me with meld3 1.0.2.  Here is what I tried.

    mnaberez@ubuntu14:~$ virtualenv --no-site-packages venv
    New python executable in venv/bin/python
    Installing setuptools, pip...done.
    mnaberez@ubuntu14:~$ cd venv
    mnaberez@ubuntu14:~/venv$ bin/pip install supervisor
    Downloading/unpacking supervisor
      Downloading supervisor-3.1.3.tar.gz (391kB): 391kB downloaded
      Running setup.py (path:/home/mnaberez/venv/build/supervisor/setup.py) egg_info for package supervisor
        
        warning: no previously-included files matching '*' found under directory 'docs/.build'
    Downloading/unpacking meld3>=0.6.5 (from supervisor)
      Downloading meld3-1.0.2-py2.py3-none-any.whl
    Installing collected packages: supervisor, meld3
      Running setup.py install for supervisor
        
        warning: no previously-included files matching '*' found under directory 'docs/.build'
        Skipping installation of /home/mnaberez/venv/lib/python2.7/site-packages/supervisor/__init__.py (namespace package)
        Installing /home/mnaberez/venv/lib/python2.7/site-packages/supervisor-3.1.3-py2.7-nspkg.pth
        Installing echo_supervisord_conf script to /home/mnaberez/venv/bin
        Installing pidproxy script to /home/mnaberez/venv/bin
        Installing supervisorctl script to /home/mnaberez/venv/bin
        Installing supervisord script to /home/mnaberez/venv/bin
    Successfully installed supervisor meld3
    Cleaning up...

    mnaberez@ubuntu14:~/venv$ bin/supervisord --help
    supervisord -- run a set of applications as daemons.
    
    Usage: bin/supervisord [options]
    
    Options:
    -c/--configuration FILENAME -- configuration file
    -n/--nodaemon -- run in the foreground (same as 'nodaemon true' in config file)
    -h/--help -- print this usage message and exit
    ...

**Comment by rtsai123** [comment]
Ok not sure why downgrading the version of meld3 works.  Here is a pip list of what is installed.

argparse (1.2.1)
backports.ssl-match-hostname (3.4.0.2)
boto (2.34.0)
chardet (2.0.1)
Cheetah (2.4.1)
cloud-init (0.7.5)
configobj (4.6.0)
distribute (0.6.10)
euca2ools (2.1.4)
glusterfs-api (3.6.0.29)
iniparse (0.3.1)
jsonpatch (1.2)
jsonpointer (1.0)
M2Crypto (0.20.2)
Markdown (2.0.1)
oauth (1.0.1)
ordereddict (1.1)
paramiko (1.7.5)
pip (6.0.8)
policycoreutils-default-encoding (0.1)
prettytable (0.7.2)
pycrypto (2.0.1)
pycurl (7.19.0)
Pygments (1.1.1)
pygpgme (0.1)
PyYAML (3.10)
requests (1.1.0)
rsa (3.1.1)
setools (1.0)
setuptools (0.6rc11)
six (1.7.3)
supervisor (3.1.2)
urlgrabber (3.9.1)
urllib3 (1.5)
virtualenv (12.0.7)
yum-metadata-parser (1.1.2)

**Comment by mnaberez** [comment]
Your output from `pip list` doesn't show any version of `meld3` installed, which would explain the `pkg_resources.DistributionNotFound: meld3>=0.6.5` error.

Supervisor requires two packages to be installed, `supervisor` and `meld3`.  You should get the `meld3` package automatically when you run a command like `pip install supervisor`.

**Comment by rtsai123** [comment]
sorry about... revised the list

**Comment by rtsai123** [comment]
I tried to install supervisor on another machine and got the same error.  Here is the info

pip install supervisor
Successfully installed supervisor-3.1.3
# /etc/init.d/supervisor start
Starting supervisor: /usr/bin/dirname: extra operand `.pid'
Try `/usr/bin/dirname --help' for more information.
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5
                                                           [FAILED]
# uname -a
Linux  2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
# rpm -qa|grep python
python-setuptools-0.6.10-3.el6.noarch
setools-libs-python-3.3.7-4.el6.x86_64
python-devel-2.6.6-52.el6.x86_64
python-pycurl-7.19.0-8.el6.x86_64
python-iniparse-0.3.1-2.1.el6.noarch
python-urllib3-1.5-7.el6.centos.noarch
python-jsonpatch-1.2-2.el6.centos.noarch
python-2.6.6-52.el6.x86_64
python-crypto-2.0.1-22.el6.x86_64
python-pygments-1.1.1-1.el6.noarch
rpm-python-4.8.0-38.el6_6.x86_64
python-boto-2.34.0-4.el6.noarch
libsemanage-python-2.0.43-4.2.el6.x86_64
python-oauth-1.0.1-1.el6.centos.noarch
python-chardet-2.0.1-1.el6.centos.noarch
newt-python-0.52.11-3.el6.x86_64
policycoreutils-python-2.0.83-19.47.el6_6.1.x86_64
python-requests-1.1.0-4.el6.centos.noarch
python-rsa-3.1.1-5.el6.noarch
python-markdown-2.0.1-3.1.el6.noarch
python-configobj-4.6.0-3.el6.noarch
python-ordereddict-1.1-2.el6.centos.noarch
python-backports-1.0-3.el6.centos.x86_64
python-argparse-1.2.1-2.el6.centos.noarch
libselinux-python-2.0.94-5.8.el6.x86_64
python-prettytable-0.7.2-1.el6.centos.noarch
python-cheetah-2.4.1-1.el6.x86_64
python-backports-ssl_match_hostname-3.4.0.2-4.el6.centos.noarch
python-urlgrabber-3.9.1-9.el6.noarch
audit-libs-python-2.3.7-5.el6.x86_64
python-six-1.7.3-1.el6.centos.noarch
python-jsonpointer-1.0-3.el6.centos.noarch
python-libs-2.6.6-52.el6.x86_64
python-paramiko-1.7.5-2.1.el6.noarch

# pip list |grep supervisor
supervisor (3.1.3)
# pip list |grep meld3
meld3 (1.0.2)

**Comment by mnaberez** [comment]
What happens on this same machine if you run it in a clean environment?  Your system already has `virtualenv` installed, try [the commands above](https://github.com/Supervisor/meld3/issues/22#issuecomment-88290852).

**Comment by rtsai123** [comment]
Putting it in a clean environment seems to work...
~# virtualenv --no-site-packages venv
New python executable in venv/bin/python
Installing setuptools, pip...done.
~#  bin/pip install supervisor
-bash: bin/pip: No such file or directory
~# cd venv
~/venv#  bin/pip install supervisor
Collecting supervisor
  Downloading supervisor-3.1.3.tar.gz (391kB)
    100% |################################| 393kB 545kB/s 
    /tmp/pip-build-vsW5r8/supervisor/setup.py:12: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      
Collecting meld3>=0.6.5 (from supervisor)
  Using cached meld3-1.0.2-py2.py3-none-any.whl
Installing collected packages: meld3, supervisor

  Running setup.py install for supervisor
    /root/venv/lib/python2.6/site-packages/setuptools/command/egg_info.py:171: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      writer = ep.load(installer=installer)
    Skipping installation of /root/venv/lib/python2.6/site-packages/supervisor/__init__.py (namespace package)
    Installing /root/venv/lib/python2.6/site-packages/supervisor-3.1.3-py2.6-nspkg.pth
    Installing echo_supervisord_conf script to /root/venv/bin
    Installing pidproxy script to /root/venv/bin
    Installing supervisorctl script to /root/venv/bin
    Installing supervisord script to /root/venv/bin
Successfully installed meld3-1.0.2 supervisor-3.1.3
opme1:~/venv#  bin/supervisord --help
supervisord -- run a set of applications as daemons.

Usage: bin/supervisord [options]

Options:
-c/--configuration FILENAME -- configuration file

**Comment by rtsai123** [comment]
Hi Mike,

Looks like setuptools was the issue.  I upgraded it and now supervisor and meld3 is happy!  Thanks for your help!

-Rob
