### ISSUE TITLE
pkg_resources.DistributionNotFound: meld3>=0.6.5

### ISSUE THREAD

**Issue by pessoa** [Supervisor/meld3#23]
just got this on a fresh supervisor install on ubuntu 12.04. Fixed it with meld3==1.0.0

```
Error: /Stage[main]/Supervisord::Service/Service[supervisord]/ensure: change from stopped to running failed: Could not start Service[supervisord]: Execution of '/etc/init.d/supervisord start' returned 1: Starting supervisor: Traceback (most recent call last):
  File "/usr/local/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line
 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5
```

**Comment by mnaberez** [comment]
This was reported in #22 and it ended up being a broken Python environment.  The meld3 1.0.2 package was checked and is valid.  In that issue, the user fixed the problem by upgrading setuptools.

**Comment by pessoa** [comment]
I already have the lastest python-setuptools for Ubuntu 12.04:
$ dpkg -l|grep python-setuptools
ii  python-setuptools                    0.6.24-1ubuntu1                   Python Distutils Enhancements (setuptools compatibility)

**Comment by Ivoz** [comment]
Unfortunately distribute 0.6.24 is still woefully out of date, it's a 2011 release. Before the two packages (distribute -> setuptools) were merged back together.

I'd guess any sort of >1.0 setuptools version might help

**Comment by tuannh99** [comment]
Yeah, upgrading setuptools fixed the problem.

**Comment by chikatambun** [comment]
@CentOS
# pip install --upgrade --force-reinstall setuptools supervisor pip supervisor-stdout Distribute

**Comment by agrwlaanchal** [comment]
my pip module is up to date but for yum package there is an error :  no module named yum. i downgraded my python from 2.7 to 2.6 and after that i am getting this problem. any suggestion, how to resolve this problem. thanks

**Comment by 52fhy** [comment]
> @CentOS
> 
> # yum reinstall python-setuptools python-setuptools-devel
> # easy_install pip
> # pip install --upgrade pip
> # pip install --upgrade --force-reinstall setuptools supervisor pip Distribute

That's not ok. I solved this by : 
``` 
wget https://pypi.python.org/packages/source/m/meld3/meld3-1.0.2.tar.gz
tar -zxf meld3-1.0.2.tar.gz
cd meld3-1.0.2
python setup.py install
```
Thanks: https://www.cnblogs.com/hubery/p/5653007.html
